pipeline
    {
        agent any

        stages {
        stage('Build code')

            {
                steps
                {   
                    // Run the build command for your C/C++ project
                    echo "Build started"
                    sh 'rm -rf /var/lib/jenkins/workspace/unittest/build/*'
                    sh 'cd /var/lib/jenkins/workspace/unittest/build/ && cmake .. && make'
                    echo "Build ended"
                }
                     post{
                             always{
                             mail to: "shreya.dhanbhar@bluebinaries.com",
                             subject: "Build Success",
                             body: "${BUILD_NUMBER}_Passed!"
                             }
                         }

            }
}
}
